query backgroundImageURL {
  errorPage {
    data {
      attributes {
        cover_image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}