query backgroundImageURL {
  homepage {
    data {
      attributes {
        background_image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}