query NewsPost($slug: String!) {
  newsPosts(filters: { slug: {eq: $slug}}) {
    data {
      attributes {
        title
        body {
          ... on ComponentPostParagraph {
            text
          }
          ... on ComponentPostGallery {
            gallery {
              data {
                attributes {
                  url
                }
              }
            }
          }
          ... on ComponentPostImage {
            image {
              data {
                attributes {
                  url
                }
              }
            }
          }
        }
      } 
    }
  }
}